// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aavbisdicplwrzyzjkij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhdmJpc2RpY3Bsd3J6eXpqa2lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MTgwMTEsImV4cCI6MjA2NzM5NDAxMX0.f24Sop4wGAmFWQ_av8UUutaJwNT1uQ3V0F4i4gVSlgc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});